// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *   KUnit tests for MS-RSVD (Remote Shared Virtual Disk) tunnel operations.
 *
 *   Tests tunnel header validation, all implemented sub-operations,
 *   not-supported stubs, unknown opcodes, response header echoing,
 *   and async tunnel dispatch.
 */

#include <kunit/test.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <linux/types.h>

/* ---- Replicated definitions from ksmbd_rsvd.h ---- */

#define RSVD_PROTOCOL_VERSION_2		0x00000002

#define RSVD_TUNNEL_GET_INITIAL_INFO                0x02001001
#define RSVD_TUNNEL_SCSI_OPERATION                  0x02001002
#define RSVD_TUNNEL_CHECK_CONNECTION_STATUS         0x02001003
#define RSVD_TUNNEL_SRB_STATUS_OPERATION            0x02001004
#define RSVD_TUNNEL_GET_DISK_INFO                   0x02001005
#define RSVD_TUNNEL_VALIDATE_DISK                   0x02001006
#define RSVD_TUNNEL_META_OPERATION_START            0x02002101
#define RSVD_TUNNEL_META_OPERATION_QUERY_PROGRESS   0x02002002
#define RSVD_TUNNEL_VHDSET_QUERY_INFORMATION        0x02002005
#define RSVD_TUNNEL_DELETE_SNAPSHOT                  0x02002006
#define RSVD_TUNNEL_CHANGE_TRACKING_GET_PARAMETERS  0x02002008
#define RSVD_TUNNEL_CHANGE_TRACKING_START           0x02002009
#define RSVD_TUNNEL_CHANGE_TRACKING_STOP            0x0200200A
#define RSVD_TUNNEL_QUERY_VIRTUAL_DISK_CHANGES      0x0200200C
#define RSVD_TUNNEL_QUERY_SAFE_SIZE                 0x0200200D

#define RSVD_TUNNEL_OPCODE_PREFIX_MASK	0xFF000000
#define RSVD_TUNNEL_OPCODE_PREFIX_VAL	0x02000000
#define RSVD_TUNNEL_OPCODE_VER_MASK	0x00FFF000
#define RSVD_TUNNEL_OPCODE_VER1		0x00001000
#define RSVD_TUNNEL_OPCODE_VER2		0x00002000

#define STATUS_BUFFER_TOO_SMALL		0xC0000023
#define STATUS_NOT_SUPPORTED		0xC00000BB
#define STATUS_INVALID_PARAMETER	0xC000000D
#define STATUS_INVALID_DEVICE_REQUEST	0xC0000010
#define STATUS_SVHDX_VERSION_MISMATCH	0xC05CFF0C

#define SVHD_SUPPORT_SHARED		0x00000001
#define SVHD_HANDLE_STATE_NONE		0x00000000
#define SVHD_DISK_TYPE_DYNAMIC		0x00000003
#define SVHD_DISK_FORMAT_VHDX		0x00000003

struct test_tunnel_header {
	__le32 OperationCode;
	__le32 Status;
	__le64 RequestId;
} __packed;

#define TUNNEL_HEADER_SIZE	sizeof(struct test_tunnel_header)

struct test_svhd_support {
	__le32 SharedVirtualDiskSupport;
	__le32 SharedVirtualDiskHandleState;
} __packed;

struct test_initial_info_rsp {
	__le32 ServerVersion;
	__le32 SectorSize;
	__le32 PhysicalSectorSize;
	__le32 Reserved;
	__le64 VirtualSize;
} __packed;

struct test_disk_info_rsp {
	__le32 DiskType;
	__le32 DiskFormat;
	__le32 BlockSize;
	__u8   LinkageId[16];
	__u8   IsMounted;
	__u8   Is4kAligned;
	__le16 Reserved;
	__le64 FileSize;
	__u8   VirtualDiskId[16];
} __packed;

struct test_validate_disk_rsp {
	__u8 IsValidDisk;
} __packed;

struct test_srb_status_rsp {
	__u8   StatusKey;
	__u8   SenseInfoAutoGenerated;
	__u8   SenseInfoExLength;
	__u8   ScsiStatus;
	__u8   SenseDataEx[20];
} __packed;

struct test_meta_op_progress_rsp {
	__le64 CurrentProgressValue;
	__le64 CompleteValue;
} __packed;

struct test_change_tracking_rsp {
	__le32 ChangeTrackingStatus;
	__le32 MostRecentEntry;
	__le32 OldestEntry;
	__le32 LogLength;
} __packed;

/* ---- Tunnel validation helper ---- */

static int test_validate_tunnel_header(void *in_buf, unsigned int in_buf_len,
				       struct test_tunnel_header **hdr)
{
	if (in_buf_len < TUNNEL_HEADER_SIZE)
		return -EINVAL;

	*hdr = (struct test_tunnel_header *)in_buf;

	if ((le32_to_cpu((*hdr)->OperationCode) & RSVD_TUNNEL_OPCODE_PREFIX_MASK)
	    != RSVD_TUNNEL_OPCODE_PREFIX_VAL)
		return -ENODEV;

	return 0;
}

/* ---- Sub-operation handlers ---- */

static __le32 test_handle_get_initial_info(void *out_buf,
					   unsigned int max_out_len,
					   unsigned int *out_len)
{
	struct test_initial_info_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_initial_info_rsp *)out_buf;
	memset(rsp, 0, sizeof(*rsp));
	rsp->ServerVersion = cpu_to_le32(RSVD_PROTOCOL_VERSION_2);
	rsp->SectorSize = cpu_to_le32(512);
	rsp->PhysicalSectorSize = cpu_to_le32(4096);
	*out_len = sizeof(*rsp);
	return 0;
}

static __le32 test_handle_check_connection(unsigned int *out_len)
{
	*out_len = 0;
	return 0;
}

static __le32 test_handle_get_disk_info(void *out_buf,
					unsigned int max_out_len,
					unsigned int *out_len)
{
	struct test_disk_info_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_disk_info_rsp *)out_buf;
	memset(rsp, 0, sizeof(*rsp));
	rsp->DiskType = cpu_to_le32(SVHD_DISK_TYPE_DYNAMIC);
	rsp->DiskFormat = cpu_to_le32(SVHD_DISK_FORMAT_VHDX);
	rsp->BlockSize = cpu_to_le32(32 * 1024 * 1024);
	rsp->Is4kAligned = 1;
	*out_len = sizeof(*rsp);
	return 0;
}

static __le32 test_handle_validate_disk(void *out_buf,
					unsigned int max_out_len,
					unsigned int *out_len)
{
	struct test_validate_disk_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_validate_disk_rsp *)out_buf;
	rsp->IsValidDisk = 0;
	*out_len = sizeof(*rsp);
	return 0;
}

static __le32 test_handle_srb_status(void *out_buf,
				     unsigned int max_out_len,
				     unsigned int *out_len)
{
	struct test_srb_status_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_srb_status_rsp *)out_buf;
	memset(rsp, 0, sizeof(*rsp));
	*out_len = sizeof(*rsp);
	return 0;
}

static __le32 test_handle_meta_op_progress(void *out_buf,
					   unsigned int max_out_len,
					   unsigned int *out_len)
{
	struct test_meta_op_progress_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_meta_op_progress_rsp *)out_buf;
	rsp->CurrentProgressValue = cpu_to_le64(100);
	rsp->CompleteValue = cpu_to_le64(100);
	*out_len = sizeof(*rsp);
	return 0;
}

static __le32 test_handle_change_tracking_params(void *out_buf,
						 unsigned int max_out_len,
						 unsigned int *out_len)
{
	struct test_change_tracking_rsp *rsp;

	if (max_out_len < sizeof(*rsp)) {
		*out_len = 0;
		return cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
	}

	rsp = (struct test_change_tracking_rsp *)out_buf;
	memset(rsp, 0, sizeof(*rsp));
	*out_len = sizeof(*rsp);
	return 0;
}

/* ---- Tunnel dispatcher ---- */

static int test_dispatch_tunnel(void *in_buf, unsigned int in_buf_len,
				unsigned int max_out_len,
				struct test_tunnel_header *rsp_hdr,
				void *payload_out,
				unsigned int *out_len,
				__le32 *rsp_status)
{
	struct test_tunnel_header *req_hdr;
	u32 opcode;
	u32 ver_bits;
	unsigned int payload_max;
	unsigned int payload_out_len = 0;
	__le32 tunnel_status;
	int ret;

	ret = test_validate_tunnel_header(in_buf, in_buf_len, &req_hdr);
	if (ret) {
		if (ret == -ENODEV) {
			*rsp_status = cpu_to_le32(STATUS_INVALID_DEVICE_REQUEST);
			return -EINVAL;
		}
		*rsp_status = cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
		return ret;
	}

	opcode = le32_to_cpu(req_hdr->OperationCode);

	ver_bits = opcode & RSVD_TUNNEL_OPCODE_VER_MASK;
	if (ver_bits != RSVD_TUNNEL_OPCODE_VER1 &&
	    ver_bits != RSVD_TUNNEL_OPCODE_VER2) {
		*rsp_status = cpu_to_le32(STATUS_SVHDX_VERSION_MISMATCH);
		return -EINVAL;
	}

	if (max_out_len < TUNNEL_HEADER_SIZE) {
		*rsp_status = cpu_to_le32(STATUS_BUFFER_TOO_SMALL);
		return -ENOSPC;
	}

	rsp_hdr->OperationCode = req_hdr->OperationCode;
	rsp_hdr->RequestId = req_hdr->RequestId;

	payload_max = max_out_len - TUNNEL_HEADER_SIZE;

	switch (opcode) {
	case RSVD_TUNNEL_GET_INITIAL_INFO:
		tunnel_status = test_handle_get_initial_info(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_CHECK_CONNECTION_STATUS:
		tunnel_status = test_handle_check_connection(&payload_out_len);
		break;
	case RSVD_TUNNEL_GET_DISK_INFO:
		tunnel_status = test_handle_get_disk_info(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_VALIDATE_DISK:
		tunnel_status = test_handle_validate_disk(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_SRB_STATUS_OPERATION:
		tunnel_status = test_handle_srb_status(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_META_OPERATION_QUERY_PROGRESS:
		tunnel_status = test_handle_meta_op_progress(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_CHANGE_TRACKING_GET_PARAMETERS:
		tunnel_status = test_handle_change_tracking_params(
			payload_out, payload_max, &payload_out_len);
		break;
	case RSVD_TUNNEL_SCSI_OPERATION:
	case RSVD_TUNNEL_META_OPERATION_START:
	case RSVD_TUNNEL_VHDSET_QUERY_INFORMATION:
	case RSVD_TUNNEL_DELETE_SNAPSHOT:
	case RSVD_TUNNEL_CHANGE_TRACKING_START:
	case RSVD_TUNNEL_CHANGE_TRACKING_STOP:
	case RSVD_TUNNEL_QUERY_VIRTUAL_DISK_CHANGES:
	case RSVD_TUNNEL_QUERY_SAFE_SIZE:
		tunnel_status = cpu_to_le32(STATUS_NOT_SUPPORTED);
		payload_out_len = 0;
		break;
	default:
		tunnel_status = cpu_to_le32(STATUS_INVALID_PARAMETER);
		payload_out_len = 0;
		break;
	}

	rsp_hdr->Status = tunnel_status;
	*out_len = TUNNEL_HEADER_SIZE + payload_out_len;
	*rsp_status = 0;
	return 0;
}

/* Helper to build a tunnel request buffer */
static void *build_tunnel_req(struct kunit *test, u32 opcode, u64 req_id,
			      unsigned int *total_len)
{
	struct test_tunnel_header *hdr;

	hdr = kunit_kzalloc(test, TUNNEL_HEADER_SIZE, GFP_KERNEL);
	KUNIT_ASSERT_NOT_NULL(test, hdr);
	hdr->OperationCode = cpu_to_le32(opcode);
	hdr->RequestId = cpu_to_le64(req_id);
	hdr->Status = 0;
	*total_len = TUNNEL_HEADER_SIZE;
	return hdr;
}

/* ---- Test cases ---- */

static void test_query_svhd_support_normal(struct kunit *test)
{
	struct test_svhd_support support;

	memset(&support, 0, sizeof(support));
	support.SharedVirtualDiskSupport = cpu_to_le32(SVHD_SUPPORT_SHARED);
	support.SharedVirtualDiskHandleState = cpu_to_le32(SVHD_HANDLE_STATE_NONE);

	KUNIT_EXPECT_EQ(test, le32_to_cpu(support.SharedVirtualDiskSupport),
			(u32)SVHD_SUPPORT_SHARED);
}

static void test_query_svhd_support_buffer_too_small(struct kunit *test)
{
	unsigned int max_out = sizeof(struct test_svhd_support) - 1;

	KUNIT_EXPECT_TRUE(test, max_out < sizeof(struct test_svhd_support));
}

static void test_tunnel_header_too_small(struct kunit *test)
{
	u8 small[4];
	struct test_tunnel_header *hdr;
	int ret;

	memset(small, 0, sizeof(small));
	ret = test_validate_tunnel_header(small, sizeof(small), &hdr);
	KUNIT_EXPECT_EQ(test, ret, -EINVAL);
}

static void test_tunnel_invalid_opcode_prefix(struct kunit *test)
{
	struct test_tunnel_header hdr;
	struct test_tunnel_header *out;
	int ret;

	memset(&hdr, 0, sizeof(hdr));
	hdr.OperationCode = cpu_to_le32(0x03001001); /* Wrong prefix: 0x03 */
	ret = test_validate_tunnel_header(&hdr, sizeof(hdr), &out);
	KUNIT_EXPECT_EQ(test, ret, -ENODEV);
}

static void test_tunnel_unknown_version_bits(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[256];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, 0x02003001, 42, &in_len);
	ret = test_dispatch_tunnel(buf, in_len, sizeof(rsp_hdr) + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, -EINVAL);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_status),
			(u32)STATUS_SVHDX_VERSION_MISMATCH);
}

static void test_tunnel_output_too_small_for_header(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHECK_CONNECTION_STATUS, 1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len, TUNNEL_HEADER_SIZE - 1,
				   &rsp_hdr, NULL, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, -ENOSPC);
}

/* ---- Implemented sub-operation tests ---- */

static void test_tunnel_get_initial_info(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[256];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	struct test_initial_info_rsp *rsp;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_GET_INITIAL_INFO, 100, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);

	rsp = (struct test_initial_info_rsp *)payload;
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp->ServerVersion),
			(u32)RSVD_PROTOCOL_VERSION_2);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp->SectorSize), (u32)512);
}

static void test_tunnel_get_initial_info_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[4];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_GET_INITIAL_INFO, 1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

static void test_tunnel_check_connection_status(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHECK_CONNECTION_STATUS, 2, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status), (u32)0);
	/* No payload expected */
	KUNIT_EXPECT_EQ(test, out_len, (unsigned int)TUNNEL_HEADER_SIZE);
}

static void test_tunnel_get_disk_info(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[256];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	struct test_disk_info_rsp *rsp;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_GET_DISK_INFO, 3, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);

	rsp = (struct test_disk_info_rsp *)payload;
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp->DiskType),
			(u32)SVHD_DISK_TYPE_DYNAMIC);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp->DiskFormat),
			(u32)SVHD_DISK_FORMAT_VHDX);
}

static void test_tunnel_get_disk_info_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[4];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_GET_DISK_INFO, 1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

static void test_tunnel_validate_disk(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	struct test_validate_disk_rsp *rsp;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_VALIDATE_DISK, 4, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	rsp = (struct test_validate_disk_rsp *)payload;
	KUNIT_EXPECT_EQ(test, rsp->IsValidDisk, (u8)0);
}

static void test_tunnel_validate_disk_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_VALIDATE_DISK, 1, &in_len);
	/* No space for payload (0 bytes after header) */
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE,
				   &rsp_hdr, NULL, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

static void test_tunnel_srb_status(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	struct test_srb_status_rsp *rsp;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_SRB_STATUS_OPERATION, 5, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	rsp = (struct test_srb_status_rsp *)payload;
	KUNIT_EXPECT_EQ(test, rsp->ScsiStatus, (u8)0);
}

static void test_tunnel_srb_status_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[2];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_SRB_STATUS_OPERATION, 1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

static void test_tunnel_meta_op_query_progress(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	struct test_meta_op_progress_rsp *rsp;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_META_OPERATION_QUERY_PROGRESS,
			       6, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	rsp = (struct test_meta_op_progress_rsp *)payload;
	KUNIT_EXPECT_EQ(test, le64_to_cpu(rsp->CurrentProgressValue), (u64)100);
	KUNIT_EXPECT_EQ(test, le64_to_cpu(rsp->CompleteValue), (u64)100);
}

static void test_tunnel_meta_op_query_progress_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[4];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_META_OPERATION_QUERY_PROGRESS,
			       1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

static void test_tunnel_change_tracking_params(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHANGE_TRACKING_GET_PARAMETERS,
			       7, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status), (u32)0);
}

static void test_tunnel_change_tracking_buffer_too_small(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[2];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHANGE_TRACKING_GET_PARAMETERS,
			       1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_BUFFER_TOO_SMALL);
}

/* ---- Not-supported stub tests ---- */

#define DEFINE_NOT_SUPPORTED_TEST(test_name, opcode_val)			\
static void test_name(struct kunit *test)					\
{										\
	struct test_tunnel_header rsp_hdr;					\
	u8 payload[64];								\
	unsigned int out_len, in_len;						\
	__le32 rsp_status;							\
	void *buf;								\
	int ret;								\
										\
	buf = build_tunnel_req(test, opcode_val, 99, &in_len);			\
	ret = test_dispatch_tunnel(buf, in_len,					\
				   TUNNEL_HEADER_SIZE + sizeof(payload),		\
				   &rsp_hdr, payload, &out_len, &rsp_status);	\
	KUNIT_EXPECT_EQ(test, ret, 0);						\
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),			\
			(u32)STATUS_NOT_SUPPORTED);				\
}

DEFINE_NOT_SUPPORTED_TEST(test_tunnel_scsi_not_supported,
			  RSVD_TUNNEL_SCSI_OPERATION)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_meta_start_not_supported,
			  RSVD_TUNNEL_META_OPERATION_START)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_vhdset_query_not_supported,
			  RSVD_TUNNEL_VHDSET_QUERY_INFORMATION)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_delete_snapshot_not_supported,
			  RSVD_TUNNEL_DELETE_SNAPSHOT)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_change_start_not_supported,
			  RSVD_TUNNEL_CHANGE_TRACKING_START)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_change_stop_not_supported,
			  RSVD_TUNNEL_CHANGE_TRACKING_STOP)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_query_changes_not_supported,
			  RSVD_TUNNEL_QUERY_VIRTUAL_DISK_CHANGES)
DEFINE_NOT_SUPPORTED_TEST(test_tunnel_query_safe_size_not_supported,
			  RSVD_TUNNEL_QUERY_SAFE_SIZE)

/* ---- Unknown opcode ---- */

static void test_tunnel_unknown_opcode(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	/* 0x02001FFF is a valid prefix+version but unknown operation */
	buf = build_tunnel_req(test, 0x02001FFF, 88, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status),
			(u32)STATUS_INVALID_PARAMETER);
}

/* ---- Response header echo ---- */

static void test_tunnel_response_header_echoed(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[64];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHECK_CONNECTION_STATUS,
			       12345, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.OperationCode),
			(u32)RSVD_TUNNEL_CHECK_CONNECTION_STATUS);
	KUNIT_EXPECT_EQ(test, le64_to_cpu(rsp_hdr.RequestId), (u64)12345);
}

/* ---- Output length includes header ---- */

static void test_tunnel_out_len_includes_header(struct kunit *test)
{
	struct test_tunnel_header rsp_hdr;
	u8 payload[256];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_GET_INITIAL_INFO, 1, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, out_len,
			(unsigned int)(TUNNEL_HEADER_SIZE +
				       sizeof(struct test_initial_info_rsp)));
}

/* ---- Async tunnel uses same dispatcher ---- */

static void test_async_tunnel_dispatches_same(struct kunit *test)
{
	/*
	 * The async tunnel handler calls the same dispatcher as sync.
	 * Verify that a known operation produces the same result via
	 * either path (both call test_dispatch_tunnel).
	 */
	struct test_tunnel_header rsp_hdr;
	u8 payload[256];
	unsigned int out_len, in_len;
	__le32 rsp_status;
	void *buf;
	int ret;

	buf = build_tunnel_req(test, RSVD_TUNNEL_CHECK_CONNECTION_STATUS, 77, &in_len);
	ret = test_dispatch_tunnel(buf, in_len,
				   TUNNEL_HEADER_SIZE + sizeof(payload),
				   &rsp_hdr, payload, &out_len, &rsp_status);
	KUNIT_EXPECT_EQ(test, ret, 0);
	KUNIT_EXPECT_EQ(test, le32_to_cpu(rsp_hdr.Status), (u32)0);
}

static struct kunit_case ksmbd_rsvd_test_cases[] = {
	KUNIT_CASE(test_query_svhd_support_normal),
	KUNIT_CASE(test_query_svhd_support_buffer_too_small),
	KUNIT_CASE(test_tunnel_header_too_small),
	KUNIT_CASE(test_tunnel_invalid_opcode_prefix),
	KUNIT_CASE(test_tunnel_unknown_version_bits),
	KUNIT_CASE(test_tunnel_output_too_small_for_header),
	KUNIT_CASE(test_tunnel_get_initial_info),
	KUNIT_CASE(test_tunnel_get_initial_info_buffer_too_small),
	KUNIT_CASE(test_tunnel_check_connection_status),
	KUNIT_CASE(test_tunnel_get_disk_info),
	KUNIT_CASE(test_tunnel_get_disk_info_buffer_too_small),
	KUNIT_CASE(test_tunnel_validate_disk),
	KUNIT_CASE(test_tunnel_validate_disk_buffer_too_small),
	KUNIT_CASE(test_tunnel_srb_status),
	KUNIT_CASE(test_tunnel_srb_status_buffer_too_small),
	KUNIT_CASE(test_tunnel_meta_op_query_progress),
	KUNIT_CASE(test_tunnel_meta_op_query_progress_buffer_too_small),
	KUNIT_CASE(test_tunnel_change_tracking_params),
	KUNIT_CASE(test_tunnel_change_tracking_buffer_too_small),
	KUNIT_CASE(test_tunnel_scsi_not_supported),
	KUNIT_CASE(test_tunnel_meta_start_not_supported),
	KUNIT_CASE(test_tunnel_vhdset_query_not_supported),
	KUNIT_CASE(test_tunnel_delete_snapshot_not_supported),
	KUNIT_CASE(test_tunnel_change_start_not_supported),
	KUNIT_CASE(test_tunnel_change_stop_not_supported),
	KUNIT_CASE(test_tunnel_query_changes_not_supported),
	KUNIT_CASE(test_tunnel_query_safe_size_not_supported),
	KUNIT_CASE(test_tunnel_unknown_opcode),
	KUNIT_CASE(test_tunnel_response_header_echoed),
	KUNIT_CASE(test_tunnel_out_len_includes_header),
	KUNIT_CASE(test_async_tunnel_dispatches_same),
	{}
};

static struct kunit_suite ksmbd_rsvd_test_suite = {
	.name = "ksmbd_rsvd",
	.test_cases = ksmbd_rsvd_test_cases,
};

kunit_test_suite(ksmbd_rsvd_test_suite);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("KUnit tests for ksmbd RSVD tunnel operations");
