# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_KSMBD_KUNIT_TEST) += ksmbd_test_ndr.o \
	ksmbd_test_acl.o \
	ksmbd_test_misc.o \
	ksmbd_test_credit.o \
	ksmbd_test_oplock.o \
	ksmbd_test_config.o \
	ksmbd_test_conn_hash.o \
	ksmbd_test_ida.o \
	ksmbd_test_pdu_common.o \
	ksmbd_test_auth.o \
	ksmbd_test_smb_common.o \
	ksmbd_test_buffer.o \
	ksmbd_test_feature.o \
	ksmbd_test_hooks.o \
	ksmbd_test_fsctl_dispatch.o \
	ksmbd_test_create_ctx.o \
	ksmbd_test_info_dispatch.o \
	ksmbd_test_unicode.o \
	ksmbd_test_vss.o \
	ksmbd_test_reparse.o \
	ksmbd_test_fruit.o
