# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_KSMBD_KUNIT_TEST) += ksmbd_test_ndr.o \
	ksmbd_test_acl.o \
	ksmbd_test_misc.o \
	ksmbd_test_credit.o \
	ksmbd_test_oplock.o \
	ksmbd_test_config.o
