/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 *   Copyright (C) 2018 Samsung Electronics Co., Ltd.
 *   Copyright (C) 2016 Namjae Jeon <linkinjeon@kernel.org>
 *
 *   MS-RSVD (Remote Shared Virtual Disk) protocol support for ksmbd
 *
 *   Implements FSCTL handlers for:
 *     - FSCTL_QUERY_SHARED_VIRTUAL_DISK_SUPPORT
 *     - FSCTL_SVHDX_SYNC_TUNNEL_REQUEST
 *     - FSCTL_SVHDX_ASYNC_TUNNEL_REQUEST
 *
 *   Reference: [MS-RSVD] Remote Shared Virtual Disk Protocol
 */

#ifndef __KSMBD_RSVD_H
#define __KSMBD_RSVD_H

#include <linux/types.h>

/*
 * RSVD protocol versions (section 2.2.1)
 */
#define RSVD_PROTOCOL_VERSION_1		0x00000001
#define RSVD_PROTOCOL_VERSION_2		0x00000002

/*
 * Tunnel operation codes (MS-RSVD section 2.2.2)
 */
#define RSVD_TUNNEL_GET_INITIAL_INFO                0x02001001
#define RSVD_TUNNEL_SCSI_OPERATION                  0x02001002
#define RSVD_TUNNEL_CHECK_CONNECTION_STATUS          0x02001003
#define RSVD_TUNNEL_SRB_STATUS_OPERATION             0x02001004
#define RSVD_TUNNEL_GET_DISK_INFO                    0x02001005
#define RSVD_TUNNEL_VALIDATE_DISK                    0x02001006
#define RSVD_TUNNEL_META_OPERATION_START             0x02002101
#define RSVD_TUNNEL_META_OPERATION_QUERY_PROGRESS    0x02002002
#define RSVD_TUNNEL_VHDSET_QUERY_INFORMATION         0x02002005
#define RSVD_TUNNEL_DELETE_SNAPSHOT                   0x02002006
#define RSVD_TUNNEL_CHANGE_TRACKING_GET_PARAMETERS   0x02002008
#define RSVD_TUNNEL_CHANGE_TRACKING_START            0x02002009
#define RSVD_TUNNEL_CHANGE_TRACKING_STOP             0x0200200A
#define RSVD_TUNNEL_QUERY_VIRTUAL_DISK_CHANGES       0x0200200C
#define RSVD_TUNNEL_QUERY_SAFE_SIZE                  0x0200200D

/*
 * Tunnel operation code validation masks (MS-RSVD section 3.2.5.5)
 *
 * The upper byte must be 0x02.
 * The middle 12 bits encode the version:
 *   0x001 = version-1 operations
 *   0x002 = version-2 operations
 */
#define RSVD_TUNNEL_OPCODE_PREFIX_MASK	0xFF000000
#define RSVD_TUNNEL_OPCODE_PREFIX_VAL	0x02000000
#define RSVD_TUNNEL_OPCODE_VER_MASK	0x00FFF000
#define RSVD_TUNNEL_OPCODE_VER1		0x00001000
#define RSVD_TUNNEL_OPCODE_VER2		0x00002000

/*
 * SVHDX_TUNNEL_OPERATION_HEADER (MS-RSVD section 2.2.4.11)
 *
 * Common header for all tunnel operation requests and responses.
 */
struct svhdx_tunnel_operation_header {
	__le32 OperationCode;
	__le32 Status;
	__le64 RequestId;
} __packed;

#define SVHDX_TUNNEL_OP_HEADER_SIZE	sizeof(struct svhdx_tunnel_operation_header)

/*
 * FSCTL_QUERY_SHARED_VIRTUAL_DISK_SUPPORT response (MS-RSVD section 2.2.4.16)
 */
struct shared_virtual_disk_support {
	__le32 SharedVirtualDiskSupport;
	__le32 SharedVirtualDiskHandleState;
} __packed;

/* SharedVirtualDiskSupport flags */
#define SVHD_SUPPORT_SHARED		0x00000001
#define SVHD_SUPPORT_CDP_SNAPSHOTS	0x00000007

/* SharedVirtualDiskHandleState values */
#define SVHD_HANDLE_STATE_NONE		0x00000000
#define SVHD_HANDLE_STATE_FILE_SHARED	0x00000001
#define SVHD_HANDLE_STATE_SHARED	0x00000003

/*
 * SVHDX_TUNNEL_INITIAL_INFO_RESPONSE (MS-RSVD section 2.2.4.15)
 *
 * Response to RSVD_TUNNEL_GET_INITIAL_INFO.
 */
struct svhdx_tunnel_initial_info_rsp {
	__le32 ServerVersion;
	__le32 SectorSize;
	__le32 PhysicalSectorSize;
	__le32 Reserved;
	__le64 VirtualSize;
} __packed;

/*
 * SVHDX_TUNNEL_DISK_INFO_RESPONSE (MS-RSVD section 2.2.4.4)
 *
 * Response to RSVD_TUNNEL_GET_DISK_INFO.
 */
struct svhdx_tunnel_disk_info_rsp {
	__le32 DiskType;
	__le32 DiskFormat;
	__le32 BlockSize;
	__u8   LinkageId[16];
	__u8   IsMounted;
	__u8   Is4kAligned;
	__le16 Reserved;
	__le64 FileSize;
	__u8   VirtualDiskId[16];
} __packed;

/* DiskType values (MS-RSVD section 2.2.4.4) */
#define SVHD_DISK_TYPE_FIXED		0x00000002
#define SVHD_DISK_TYPE_DYNAMIC		0x00000003
#define SVHD_DISK_TYPE_DIFFERENCING	0x00000004

/* DiskFormat values */
#define SVHD_DISK_FORMAT_VHDX		0x00000003

/*
 * SVHDX_TUNNEL_SCSI_REQUEST (MS-RSVD section 2.2.4.7)
 */
struct svhdx_tunnel_scsi_request {
	__le16 Length;
	__u8   Reserved1;
	__u8   CDBLength;
	__u8   SenseInfoExLength;
	__u8   DataIn;
	__u8   Reserved2;
	__u8   SrbFlags;
	__le32 DataTransferLength;
	__u8   CDB[16];
	__u8   Reserved3[4];
	__u8   DataBuffer[];
} __packed;

/* DataIn values */
#define SVHD_SCSI_DATA_WRITE		0x00
#define SVHD_SCSI_DATA_READ		0x01
#define SVHD_SCSI_DATA_BIDIRECTIONAL	0x02

/*
 * SVHDX_TUNNEL_SCSI_RESPONSE (MS-RSVD section 2.2.4.8)
 */
struct svhdx_tunnel_scsi_response {
	__le16 Length;
	__u8   SrbStatus;
	__u8   ScsiStatus;
	__u8   CDBLength;
	__u8   SenseInfoExLength;
	__u8   DataIn;
	__u8   Reserved;
	__le32 DataTransferLength;
	__u8   SenseDataEx[20];
	__u8   DataBuffer[];
} __packed;

/*
 * SVHDX_TUNNEL_VALIDATE_DISK_RESPONSE (MS-RSVD section 2.2.4.5)
 */
struct svhdx_tunnel_validate_disk_rsp {
	__u8 IsValidDisk;
} __packed;

/*
 * SVHDX_TUNNEL_SRB_STATUS_RESPONSE (MS-RSVD section 2.2.4.6)
 */
struct svhdx_tunnel_srb_status_rsp {
	__u8   StatusKey;
	__u8   SenseInfoAutoGenerated;
	__u8   SenseInfoExLength;
	__u8   ScsiStatus;
	__u8   SenseDataEx[20];
} __packed;

/*
 * SVHDX_META_OPERATION_QUERY_PROGRESS_RESPONSE (MS-RSVD section 2.2.4.3)
 */
struct svhdx_tunnel_meta_op_progress_rsp {
	__le64 CurrentProgressValue;
	__le64 CompleteValue;
} __packed;

/*
 * SVHDX_TUNNEL_CHECK_CONNECTION_STATUS_RESPONSE
 *
 * This is just the tunnel header with Status set to success/failure.
 * No additional fields.
 */

/*
 * SVHDX_CHANGE_TRACKING_GET_PARAMETERS_RESPONSE (MS-RSVD section 2.2.4.22)
 */
struct svhdx_tunnel_change_tracking_params_rsp {
	__le32 ChangeTrackingStatus;
	__le32 MostRecentEntry;
	__le32 OldestEntry;
	__le32 LogLength;
} __packed;

/* SRB status codes (commonly referenced) */
#define SRB_STATUS_SUCCESS		0x00
#define SRB_STATUS_PENDING		0x00
#define SRB_STATUS_ABORTED		0x02
#define SRB_STATUS_ERROR		0x04
#define SRB_STATUS_INVALID_REQUEST	0x06

/* NTSTATUS values used in RSVD */
#define STATUS_SVHDX_ERROR_STORED	0xC05CFF00
#define STATUS_SVHDX_VERSION_MISMATCH	0xC05CFF0C

/**
 * ksmbd_rsvd_init() - Initialize RSVD subsystem
 *
 * Registers FSCTL handlers for RSVD operations:
 *   - FSCTL_QUERY_SHARED_VIRTUAL_DISK_SUPPORT
 *   - FSCTL_SVHDX_SYNC_TUNNEL_REQUEST
 *   - FSCTL_SVHDX_ASYNC_TUNNEL_REQUEST
 *
 * Return: 0 on success, negative errno on failure
 */
int ksmbd_rsvd_init(void);

/**
 * ksmbd_rsvd_exit() - Tear down RSVD subsystem
 *
 * Unregisters all RSVD FSCTL handlers.
 */
void ksmbd_rsvd_exit(void);

#endif /* __KSMBD_RSVD_H */
